"""Schema-backed fixture helpers for MCP server tests.

The canonical column list for every FinRatioAnalysis method lives in
library_schema.json (generated by scripts/snapshot_library_schema.py).
Mock DataFrames in conftest.py MUST be built from this schema so they
cannot drift from the real library surface.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

_SCHEMA_PATH = Path(__file__).parent / "library_schema.json"


def load_schema() -> dict[str, dict[str, Any]]:
    if not _SCHEMA_PATH.exists():
        raise FileNotFoundError(
            f"Missing {_SCHEMA_PATH}. Run:\n"
            f"    python scripts/snapshot_library_schema.py\n"
            f"to regenerate it from the real FinRatioAnalysis library."
        )
    return json.loads(_SCHEMA_PATH.read_text(encoding="utf-8"))


def columns_for(method: str) -> list[str]:
    schema = load_schema()
    if method not in schema:
        raise KeyError(f"No schema entry for method '{method}'. Re-run snapshot script.")
    cols = schema[method]["columns"]
    if not cols:
        raise ValueError(
            f"Schema for '{method}' has empty columns — snapshot captured an empty "
            f"DataFrame. Re-run snapshot against a ticker with complete data."
        )
    return cols


def make_timeseries_df(method: str, n_periods: int = 3, seed: int = 0) -> pd.DataFrame:
    """Build a mock time-series DataFrame with the REAL column names for `method`."""
    cols = columns_for(method)
    dates = pd.to_datetime(
        [f"{2022 + i}-01-01" for i in range(n_periods)]
    )
    rng = np.random.default_rng(seed)
    data = {c: rng.uniform(0.05, 0.5, size=n_periods) for c in cols}
    return pd.DataFrame(data, index=dates)


def make_snapshot_df(method: str, symbol: str = "AAPL", seed: int = 0) -> pd.DataFrame:
    """Build a single-row snapshot DataFrame with the REAL column names for `method`."""
    cols = columns_for(method)
    rng = np.random.default_rng(seed)
    row: dict[str, Any] = {}
    for c in cols:
        if c == "Symbol":
            row[c] = symbol
        elif c == "Zone":
            row[c] = "Safe"
        else:
            row[c] = float(rng.uniform(0.05, 5.0))
    return pd.DataFrame([row])
