"""Pytest configuration and shared fixtures for MCP server tests.

Mock DataFrames are built from tests_mcp/fixtures/library_schema.json, which
is a snapshot of the REAL FinRatioAnalysis column surface (generated by
scripts/snapshot_library_schema.py). This prevents tests from silently
passing against invented column names that don't match the library.

If library_schema.json is missing, the fixture helpers raise FileNotFoundError
with regeneration instructions — by design, so drift is loud.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pandas as pd
import pytest

from tests_mcp.fixtures import make_snapshot_df, make_timeseries_df


# --- Time-series fixtures -------------------------------------------------

@pytest.fixture
def mock_return_ratios_df() -> pd.DataFrame:
    return make_timeseries_df("return_ratios", seed=1)


@pytest.fixture
def mock_efficiency_ratios_df() -> pd.DataFrame:
    return make_timeseries_df("efficiency_ratios", seed=2)


@pytest.fixture
def mock_leverage_ratios_df() -> pd.DataFrame:
    return make_timeseries_df("leverage_ratios", seed=3)


@pytest.fixture
def mock_liquidity_ratios_df() -> pd.DataFrame:
    return make_timeseries_df("liquidity_ratios", seed=4)


@pytest.fixture
def mock_ccc_df() -> pd.DataFrame:
    return make_timeseries_df("ccc", seed=5)


@pytest.fixture
def mock_historical_valuation_metrics_df() -> pd.DataFrame:
    return make_timeseries_df("historical_valuation_metrics", seed=6)


# --- Snapshot fixtures ----------------------------------------------------

@pytest.fixture
def mock_valuation_growth_metrics_df() -> pd.DataFrame:
    return make_snapshot_df("valuation_growth_metrics", seed=7)


@pytest.fixture
def mock_z_score_df() -> pd.DataFrame:
    return make_snapshot_df("z_score", seed=8)


@pytest.fixture
def mock_capm_df() -> pd.DataFrame:
    return make_snapshot_df("capm", seed=9)


@pytest.fixture
def mock_wacc_df() -> pd.DataFrame:
    return make_snapshot_df("wacc", seed=10)


# --- Composite fixtures ---------------------------------------------------

@pytest.fixture
def mock_finratioanalysis(
    mock_return_ratios_df,
    mock_efficiency_ratios_df,
    mock_leverage_ratios_df,
    mock_liquidity_ratios_df,
    mock_ccc_df,
    mock_historical_valuation_metrics_df,
    mock_valuation_growth_metrics_df,
    mock_z_score_df,
    mock_capm_df,
    mock_wacc_df,
):
    """Mock FinRatioAnalysis class with schema-backed DataFrame responses."""
    mock_instance = MagicMock()
    mock_instance.symbol = "AAPL"

    mock_instance.return_ratios.return_value = mock_return_ratios_df
    mock_instance.efficiency_ratios.return_value = mock_efficiency_ratios_df
    mock_instance.leverage_ratios.return_value = mock_leverage_ratios_df
    mock_instance.liquidity_ratios.return_value = mock_liquidity_ratios_df
    mock_instance.ccc.return_value = mock_ccc_df
    mock_instance.historical_valuation_metrics.return_value = mock_historical_valuation_metrics_df
    mock_instance.valuation_growth_metrics.return_value = mock_valuation_growth_metrics_df
    mock_instance.z_score.return_value = mock_z_score_df
    mock_instance.capm.return_value = mock_capm_df
    mock_instance.wacc.return_value = mock_wacc_df

    return mock_instance


@pytest.fixture
def mcp_server(mock_finratioanalysis):
    """FastMCP server with FinRatioAnalysis patched to the schema-backed mock."""
    with patch("finratioanalysis_mcp.server.FinRatioAnalysis") as mock_class:
        mock_class.return_value = mock_finratioanalysis

        from finratioanalysis_mcp.server import mcp
        yield mcp
